// Gramática en acción (estilo Cambridge A1–C1): cada tema trae una explicación corta y ejercicios.
// Tipos: c = elegir la opción correcta ("frase con ___", [opciones], índice correcto, explicación)
//        o = ordenar palabras ("frase completa", "traducción")
//        p = escena con dibujo ("dibujos", "pregunta", "respuesta para ordenar", "traducción")
window.GRAMMAR=[
{id:'be',lv:'A1',n:'Verb to be',es:'Ser y estar: am, is, are',e:'🙋',tip:'Usa am con I, is con he, she e it, y are con you, we y they. En negativo agrega not: I am not, she isn\'t, they aren\'t.',x:[
['c','I ___ from Mexico.',['am','is','are'],0,'Con I siempre va am.'],
['c','My sister ___ a nurse.',['am','is','are'],1,'My sister = she, por eso is.'],
['c','We ___ very tired today.',['is','are','am'],1,'Con we se usa are.'],
['c','___ your parents at home?',['Is','Am','Are'],2,'Your parents = they, así que la pregunta empieza con Are.'],
['o','She is not my teacher.','Ella no es mi maestra.'],
['o','Are you ready for the party?','¿Estás listo para la fiesta?'],
['p','👩‍🏫📚','Who is she?','She is a teacher.','Ella es maestra.'],
['p','🐶😴','How is the dog?','The dog is very sleepy.','El perro tiene mucho sueño.']]},
{id:'pres',lv:'A1',n:'Present simple',es:'Rutinas y hechos: I work, she works',e:'🔁',tip:'Para rutinas y cosas que siempre son ciertas. Con he, she e it el verbo lleva -s: she works, he watches. Para negar y preguntar usa do / does: She doesn\'t work. Do you work?',x:[
['c','My brother ___ in a bank.',['work','works','working'],1,'He/she/it lleva -s en presente simple.'],
['c','They ___ like spicy food.',['doesn\'t','don\'t','isn\'t'],1,'Con they se niega con don\'t.'],
['c','___ she speak English?',['Do','Is','Does'],2,'Pregunta con she: Does.'],
['c','Water ___ at 100 degrees.',['boil','boils','is boil'],1,'Un hecho que siempre es cierto: boils.'],
['o','I usually have breakfast at seven.','Normalmente desayuno a las siete.'],
['o','Does your father drive to work?','¿Tu papá maneja al trabajo?'],
['p','🧑‍🍳🍳🌅','What does he do every morning?','He cooks eggs every morning.','Él cocina huevos todas las mañanas.'],
['p','👧🚌🏫','How does she go to school?','She goes to school by bus.','Ella va a la escuela en camión.']]},
{id:'cont',lv:'A1',n:'Present continuous',es:'Lo que pasa ahora: I am eating',e:'🎬',tip:'Para lo que está pasando en este momento: am / is / are + verbo con -ing. Ejemplo: They are playing soccer right now.',x:[
['c','Look! The baby ___.',['sleeps','is sleeping','sleep'],1,'Está pasando ahora, por eso is sleeping.'],
['c','What ___ you doing?',['do','are','is'],1,'Con you: are you doing.'],
['c','We ___ watching TV at the moment.',['are','is','do'],0,'We are + -ing.'],
['c','She ___ working today. She is at home.',['isn\'t','doesn\'t','aren\'t'],0,'Negativo de is + -ing: isn\'t working.'],
['o','They are playing soccer in the park.','Están jugando futbol en el parque.'],
['p','👩🍳👨📖','What are they doing?','She is cooking and he is reading.','Ella está cocinando y él está leyendo.'],
['p','👦👧🏊','What are the children doing?','The children are swimming in the pool.','Los niños están nadando en la alberca.'],
['p','🧑💻☕','What is the man doing?','The man is drinking coffee and working.','El hombre está tomando café y trabajando.'],
['p','👫💃🎶','What are they doing?','They are dancing to the music.','Están bailando con la música.'],
['p','👵📱😂','What is the grandmother doing?','She is laughing at her phone.','Ella se está riendo con su celular.']]},
{id:'there',lv:'A1',n:'There is / there are',es:'Hay: there is, there are',e:'📦',tip:'There is para una cosa (singular) y there are para varias (plural). Pregunta: Is there…? Are there…?',x:[
['c','There ___ a cat under the table.',['is','are','be'],0,'Un gato, singular: there is.'],
['c','There ___ three apples in the bowl.',['is','are','am'],1,'Varias manzanas: there are.'],
['c','___ there any milk in the fridge?',['Are','Is','Do'],1,'Milk no se cuenta, va con is.'],
['o','There are two beds in my room.','Hay dos camas en mi cuarto.'],
['p','🛋️🐱📺','What is there in the living room?','There is a cat on the sofa.','Hay un gato en el sillón.'],
['p','🍎🍎🍎🥣','What is in the bowl?','There are three apples in the bowl.','Hay tres manzanas en el tazón.']]},
{id:'prep',lv:'A1',n:'Prepositions of place',es:'En, sobre, debajo, entre…',e:'📍',tip:'in = dentro, on = sobre, under = debajo, next to = al lado, between = entre, behind = detrás, in front of = enfrente.',x:[
['c','The keys are ___ the table. (sobre)',['in','on','under'],1,'Sobre una superficie: on.'],
['c','The dog is ___ the bed. (debajo)',['under','on','between'],0,'Debajo: under.'],
['c','The bank is ___ the café and the school.',['next','between','behind'],1,'Entre dos cosas: between.'],
['c','My phone is ___ my bag.',['in','on','at'],0,'Dentro de algo: in.'],
['o','The car is in front of the house.','El carro está enfrente de la casa.'],
['p','📦🐱','Where is the cat?','The cat is in the box.','El gato está dentro de la caja.'],
['p','🌳🧒','Where is the boy?','The boy is behind the tree.','El niño está detrás del árbol.']]},
{id:'can',lv:'A1',n:'Can / can\'t',es:'Habilidad y permiso',e:'💪',tip:'Can + verbo sin to, igual para todas las personas: She can swim. Negativo: can\'t. Pregunta: Can you help me?',x:[
['c','My grandma ___ use a computer.',['cans','can','can to'],1,'Can no cambia y no lleva to.'],
['c','___ I open the window?',['Can','Do','Am'],0,'Pedir permiso: Can I…?'],
['c','Penguins can\'t ___.',['flying','to fly','fly'],2,'Después de can va el verbo base.'],
['o','Can you speak more slowly please?','¿Puedes hablar más despacio, por favor?'],
['p','🐧🏊','What can penguins do?','Penguins can swim but they can\'t fly.','Los pingüinos pueden nadar pero no pueden volar.']]},
{id:'past',lv:'A2',n:'Past simple',es:'El pasado: I worked, I went',e:'⏪',tip:'Verbos regulares agregan -ed (worked, played). Los irregulares cambian (go → went, eat → ate). Para negar y preguntar usa did + verbo base: I didn\'t go. Did you eat?',x:[
['c','Yesterday I ___ to the beach.',['go','went','goed'],1,'Go es irregular: went.'],
['c','We ___ a movie last night.',['watched','watch','watching'],0,'Regular: watch → watched.'],
['c','Did you ___ the email?',['sent','sending','send'],2,'Después de did va el verbo base.'],
['c','She ___ come to the party.',['didn\'t','doesn\'t','wasn\'t'],0,'Pasado negativo: didn\'t + verbo base.'],
['o','We visited my grandparents last weekend.','Visitamos a mis abuelos el fin de semana pasado.'],
['o','What did you eat for dinner yesterday?','¿Qué cenaste ayer?'],
['p','🏖️👨‍👩‍👧📸','What did the family do last summer?','They went to the beach and took photos.','Fueron a la playa y tomaron fotos.'],
['p','🎂🎉👧','What happened yesterday?','She had a birthday party yesterday.','Ayer tuvo una fiesta de cumpleaños.']]},
{id:'pastc',lv:'A2',n:'Past continuous',es:'Estaba haciendo: I was sleeping',e:'🌧️',tip:'Was / were + -ing para algo que estaba en progreso en el pasado. Muchas veces se interrumpe con past simple: I was cooking when the phone rang.',x:[
['c','I ___ sleeping when you called.',['was','were','am'],0,'Con I: was.'],
['c','They ___ playing when it started to rain.',['was','were','are'],1,'Con they: were.'],
['c','What were you ___ at 8 pm?',['do','did','doing'],2,'Were + -ing: doing.'],
['o','She was reading when the lights went out.','Ella estaba leyendo cuando se fue la luz.'],
['p','🚿📞','What was he doing when the phone rang?','He was taking a shower when the phone rang.','Se estaba bañando cuando sonó el teléfono.']]},
{id:'comp',lv:'A2',n:'Comparatives',es:'Comparar: bigger than, more expensive than',e:'⚖️',tip:'Adjetivos cortos: + -er + than (tall → taller than). Si terminan en consonante-vocal-consonante, se dobla la letra (big → bigger). Que terminan en -y: happy → happier. Adjetivos largos: more + adjetivo + than (more expensive than). Irregulares: good → better, bad → worse, far → farther.',x:[
['c','An elephant is ___ than a horse.',['big','bigger','more big'],1,'Big es corto: bigger (se dobla la g).'],
['c','This phone is ___ than that one.',['expensiver','more expensive','most expensive'],1,'Expensive es largo: more expensive than.'],
['c','My brother is ___ than me.',['taller','more tall','tallest'],0,'Tall es corto: taller than.'],
['c','Today the weather is ___ than yesterday.',['gooder','more good','better'],2,'Good es irregular: better.'],
['c','English is ___ than Chinese for me.',['easyer','easier','more easy'],1,'Easy termina en -y: easier.'],
['c','The traffic today is ___ than last week.',['badder','worse','more bad'],1,'Bad es irregular: worse.'],
['o','My sister is younger than my brother.','Mi hermana es más joven que mi hermano.'],
['o','A plane is faster than a train.','Un avión es más rápido que un tren.'],
['p','🐘🐭','Compare the animals. (big)','The elephant is bigger than the mouse.','El elefante es más grande que el ratón.'],
['p','🚗💲💲💲🚲💲','Compare them. (expensive)','The car is more expensive than the bike.','El carro es más caro que la bicicleta.'],
['p','🐢🐇','Compare them. (fast)','The rabbit is faster than the turtle.','El conejo es más rápido que la tortuga.']]},
{id:'asas',lv:'A2',n:'As … as',es:'Tan… como: as big as',e:'🟰',tip:'Para decir que dos cosas son iguales: as + adjetivo + as. She is as tall as her brother. En negativo, que no son iguales: not as… as. My car isn\'t as fast as yours.',x:[
['c','Tom is ___ tall as his father.',['so','as','than'],1,'Igualdad: as tall as.'],
['c','My house isn\'t as big ___ yours.',['than','like','as'],2,'La estructura es as… as.'],
['c','This test was ___ difficult as the last one.',['as','more','the most'],0,'Igual de difícil: as difficult as.'],
['c','Your phone is ___ as mine.',['as expensive','more expensive','expensiver'],0,'as + adjetivo (sin cambiarlo) + as.'],
['o','My sister is as smart as my brother.','Mi hermana es tan inteligente como mi hermano.'],
['o','The movie was not as good as the book.','La película no fue tan buena como el libro.'],
['p','👦📏👦','Compare the twins. (tall)','He is as tall as his brother.','Él es tan alto como su hermano.'],
['p','🐱🐶💨','The dog is fast. Compare. (fast)','The cat is not as fast as the dog.','El gato no es tan rápido como el perro.']]},
{id:'sup',lv:'A2',n:'Superlatives',es:'El más: the biggest, the most expensive',e:'🏆',tip:'Para el número uno de un grupo: the + adjetivo-est (the tallest) o the most + adjetivo largo (the most beautiful). Irregulares: the best, the worst, the farthest.',x:[
['c','Mount Everest is ___ mountain in the world.',['the highest','the higher','highest'],0,'Superlativo: the highest.'],
['c','This is ___ restaurant in town.',['the most expensive','the expensivest','more expensive'],0,'Adjetivo largo: the most expensive.'],
['c','She is the ___ student in the class.',['goodest','best','better'],1,'Good → the best.'],
['c','That was the ___ day of my life!',['happiest','happyest','most happy'],0,'Happy → the happiest.'],
['o','The blue whale is the biggest animal in the world.','La ballena azul es el animal más grande del mundo.'],
['p','🐭🐶🐘','Which is the biggest?','The elephant is the biggest animal.','El elefante es el animal más grande.'],
['p','🥇🥈🥉','Who won?','She was the fastest runner in the race.','Ella fue la corredora más rápida de la carrera.']]},
{id:'tooe',lv:'A2',n:'Too / enough',es:'Demasiado y suficiente',e:'🌡️',tip:'too + adjetivo = demasiado (It\'s too hot). adjetivo + enough = suficiente (He isn\'t old enough). enough + sustantivo: We don\'t have enough money.',x:[
['c','This coffee is ___ hot to drink.',['too','enough','very much'],0,'Demasiado caliente: too hot.'],
['c','He isn\'t old ___ to drive.',['too','enough','so'],1,'Enough va después del adjetivo.'],
['c','We don\'t have ___ chairs for everyone.',['too','enough','very'],1,'Enough va antes del sustantivo.'],
['o','These shoes are too small for me.','Estos zapatos me quedan demasiado chicos.'],
['p','👕🧍‍♂️','Why can\'t he wear the shirt?','The shirt is too small for him.','La camisa le queda demasiado chica.']]},
{id:'fut',lv:'A2',n:'Going to / will',es:'El futuro: planes y predicciones',e:'🔮',tip:'Going to para planes que ya decidiste y para lo que ves que va a pasar (Look at the clouds! It\'s going to rain). Will para decisiones del momento, promesas y predicciones (I\'ll help you. I think you will pass).',x:[
['c','I ___ visit my aunt next Sunday. I already bought the ticket.',['will','am going to','go'],1,'Plan decidido: going to.'],
['c','The phone is ringing. — I ___ answer it!',['\'ll','am going to','answer'],0,'Decisión del momento: will.'],
['c','Look at those clouds! It ___ rain.',['will','is going to','rains'],1,'Lo ves venir: going to.'],
['c','I promise I ___ call you tomorrow.',['will','am going','calling'],0,'Promesa: will.'],
['o','We are going to travel to Cancun in December.','Vamos a viajar a Cancún en diciembre.'],
['p','☁️⛈️👩‍🦰☂️','What is going to happen?','It is going to rain soon.','Va a llover pronto.']]},
{id:'quant',lv:'A2',n:'Much, many, some, any',es:'Cantidades',e:'🧮',tip:'Many con cosas que se cuentan (many apples). Much con cosas que no se cuentan (much water), sobre todo en preguntas y negativos. Some en afirmativos, any en preguntas y negativos. A lot of sirve para las dos.',x:[
['c','How ___ apples do you want?',['much','many','any'],1,'Apples se cuentan: many.'],
['c','How ___ money do you have?',['many','much','some'],1,'Money no se cuenta: much.'],
['c','There isn\'t ___ milk left.',['some','any','many'],1,'Negativo: any.'],
['c','I bought ___ bread for breakfast.',['any','some','many'],1,'Afirmativo: some.'],
['o','There are a lot of people at the concert.','Hay mucha gente en el concierto.']]},
{id:'modal',lv:'A2',n:'Must, have to, should',es:'Obligación y consejos',e:'⚠️',tip:'Must y have to = tener que (obligación). Mustn\'t = está prohibido. Don\'t have to = no es necesario. Should = deberías (consejo).',x:[
['c','You ___ smoke in the hospital. It\'s forbidden.',['mustn\'t','don\'t have to','shouldn\'t to'],0,'Prohibido: mustn\'t.'],
['c','Tomorrow is Sunday. I ___ go to work.',['mustn\'t','don\'t have to','must'],1,'No es necesario: don\'t have to.'],
['c','You look tired. You ___ go to bed early.',['should','must to','have'],0,'Consejo: should.'],
['c','She ___ wear a uniform at work.',['have to','has to','must to'],1,'Con she: has to.'],
['o','You should drink more water every day.','Deberías tomar más agua cada día.'],
['p','🤒🛌','What should he do?','He should stay in bed and rest.','Debería quedarse en cama y descansar.']]},
{id:'perf',lv:'B1',n:'Present perfect',es:'Experiencias: I have been to…',e:'✅',tip:'Have / has + participio. Para experiencias (Have you ever been to Paris?), cosas recientes (I\'ve just eaten) y desde cuándo (I have lived here for five years / since 2020). Ever, never, just, already, yet son sus amigos.',x:[
['c','Have you ever ___ sushi?',['ate','eaten','eat'],1,'Participio de eat: eaten.'],
['c','She ___ lived here since 2019.',['has','have','is'],0,'Con she: has.'],
['c','I have known him ___ ten years.',['since','for','from'],1,'Con una cantidad de tiempo: for.'],
['c','We haven\'t finished ___.',['already','yet','just'],1,'Al final de un negativo: yet.'],
['c','I ___ to London twice.',['have been','have gone','was been'],0,'Experiencia de visitar: have been.'],
['o','I have never seen the ocean.','Nunca he visto el mar.'],
['o','Have you finished your homework yet?','¿Ya terminaste tu tarea?'],
['p','✈️🗼🧳','What experience has she had?','She has been to Paris three times.','Ha ido a París tres veces.']]},
{id:'cond',lv:'B1',n:'Conditionals',es:'Si…: if it rains, if I had…',e:'🔀',tip:'Zero: if + presente, presente (If you heat ice, it melts). First: if + presente, will (If it rains, I\'ll stay home). Second: if + pasado, would (If I had money, I would travel). Third: if + had + participio, would have (If I had studied, I would have passed).',x:[
['c','If it rains tomorrow, we ___ stay at home.',['will','would','are'],0,'Primer condicional: will.'],
['c','If I ___ rich, I would buy a big house.',['am','were','will be'],1,'Segundo condicional: were.'],
['c','If you heat water, it ___.',['boils','would boil','boiled'],0,'Hecho general: presente.'],
['c','If she had studied, she ___ the exam.',['would pass','would have passed','will pass'],1,'Tercer condicional: would have passed.'],
['o','If I see him I will tell him.','Si lo veo, le digo.'],
['o','What would you do if you won the lottery?','¿Qué harías si te ganaras la lotería?']]},
{id:'used',lv:'B1',n:'Used to',es:'Lo que hacías antes',e:'📼',tip:'Used to + verbo base = algo que hacías antes y ya no (I used to play soccer). Negativo: didn\'t use to. Pregunta: Did you use to…?',x:[
['c','I ___ live in Monterrey, but now I live in CDMX.',['use to','used to','was used'],1,'Afirmativo: used to.'],
['c','Did you ___ have long hair?',['used to','use to','using'],1,'Con did: use to.'],
['o','My father used to work in a factory.','Mi papá trabajaba en una fábrica.'],
['p','🧒⚽➡️🧔💼','How has he changed?','He used to play soccer but now he works.','Antes jugaba futbol, pero ahora trabaja.']]},
{id:'passive',lv:'B1',n:'Passive voice',es:'Voz pasiva: it was built',e:'🏗️',tip:'Be + participio. Importa la acción, no quién la hace: The Pyramids were built thousands of years ago. English is spoken all over the world. Quien lo hace va con by.',x:[
['c','This bridge ___ in 1990.',['built','was built','is build'],1,'Pasado pasivo: was built.'],
['c','English ___ in many countries.',['speaks','is spoken','is speaking'],1,'Presente pasivo: is spoken.'],
['c','The letter was written ___ my grandfather.',['by','for','from'],0,'Quien lo hace: by.'],
['o','The car was repaired yesterday.','El carro fue reparado ayer.']]},
{id:'rel',lv:'B1',n:'Relative clauses',es:'Who, which, where, whose',e:'🔗',tip:'who para personas, which para cosas, where para lugares, whose para pertenencia. That puede reemplazar a who y which.',x:[
['c','The woman ___ lives next door is a doctor.',['which','who','where'],1,'Persona: who.'],
['c','This is the restaurant ___ we met.',['where','which','who'],0,'Lugar: where.'],
['c','I have a friend ___ father is a pilot.',['who','whose','which'],1,'Pertenencia: whose.'],
['o','The phone which I bought is very fast.','El celular que compré es muy rápido.']]},
{id:'reported',lv:'B2',n:'Reported speech',es:'Contar lo que alguien dijo',e:'💬',tip:'Al contar lo que alguien dijo, el verbo da un paso al pasado: "I am tired" → She said (that) she was tired. "I will call" → He said he would call. Say no lleva persona; tell sí: He told me…',x:[
['c','"I am hungry." → He said he ___ hungry.',['is','was','has been'],1,'Am → was.'],
['c','"We will help." → They said they ___ help.',['will','would','can'],1,'Will → would.'],
['c','She ___ me that she was busy.',['said','told','spoke'],1,'Con persona: told me.'],
['o','He said that he was working.','Dijo que estaba trabajando.']]},
{id:'tags',lv:'B2',n:'Question tags',es:'¿Verdad?: isn\'t it?, don\'t you?',e:'❔',tip:'Para pedir confirmación: si la frase es positiva, la etiqueta es negativa, y al revés. It\'s cold, isn\'t it? You don\'t smoke, do you?',x:[
['c','It\'s a beautiful day, ___?',['is it','isn\'t it','doesn\'t it'],1,'Positiva → etiqueta negativa.'],
['c','You don\'t like coffee, ___?',['do you','don\'t you','are you'],0,'Negativa → etiqueta positiva.'],
['c','She can swim, ___?',['can she','can\'t she','doesn\'t she'],1,'Con can: can\'t she.'],
['o','You are coming tonight aren\'t you?','Vas a venir hoy en la noche, ¿verdad?']]},
{id:'wish',lv:'B2',n:'Wish / if only',es:'Deseos y arrepentimientos',e:'🌠',tip:'Wish + pasado para el presente (I wish I had a car = ojalá tuviera). Wish + had + participio para el pasado (I wish I had studied = ojalá hubiera estudiado).',x:[
['c','I wish I ___ taller.',['am','were','will be'],1,'Deseo sobre el presente: were.'],
['c','I wish I ___ harder for the exam.',['studied','had studied','study'],1,'Arrepentimiento del pasado: had studied.'],
['o','I wish I could speak perfect English.','Ojalá pudiera hablar inglés perfecto.']]},
];
