// Fluent — para hablar bien: frases para situaciones reales y laboratorio de pronunciación.
// Situaciones: cada frase es "inglés|español". Pronunciación: pares mínimos "palabra A|palabra B|significado A|significado B".
window.SITUATIONS=[
{id:'doctor',n:'En el doctor',en:'At the doctor',e:'🩺',p:[
'I need to make an appointment.|Necesito hacer una cita.','I have a terrible headache.|Tengo un dolor de cabeza terrible.','It hurts here.|Me duele aquí.','I have had a fever since yesterday.|Tengo fiebre desde ayer.','I feel dizzy.|Me siento mareado.','I am allergic to penicillin.|Soy alérgico a la penicilina.','How often should I take this medicine?|¿Cada cuánto tomo esta medicina?','Twice a day, after meals.|Dos veces al día, después de comer.','Do I need a prescription?|¿Necesito receta?','I think I sprained my ankle.|Creo que me torcí el tobillo.','When will I get the results?|¿Cuándo me dan los resultados?','I feel much better now, thank you.|Ya me siento mucho mejor, gracias.']},
{id:'job',n:'Entrevista de trabajo',en:'Job interview',e:'💼',p:[
'Tell me about yourself.|Háblame de ti.','I have five years of experience in sales.|Tengo cinco años de experiencia en ventas.','I am a fast learner and I work well in a team.|Aprendo rápido y trabajo bien en equipo.','My greatest strength is my communication.|Mi mayor fortaleza es la comunicación.','I sometimes take on too much work.|A veces me echo demasiado trabajo.','Why do you want to work here?|¿Por qué quieres trabajar aquí?','I admire your company\'s values.|Admiro los valores de su empresa.','Where do you see yourself in five years?|¿Dónde te ves en cinco años?','I would like to grow into a leadership role.|Me gustaría crecer a un puesto de liderazgo.','What are the next steps?|¿Cuáles son los siguientes pasos?','Thank you for your time.|Gracias por su tiempo.','I look forward to hearing from you.|Quedo atento a su respuesta.']},
{id:'airport',n:'Aeropuerto y avión',en:'Airport',e:'✈️',p:[
'I would like to check in, please.|Quisiera documentar, por favor.','Can I have a window seat?|¿Me da un asiento de ventanilla?','How many bags can I check?|¿Cuántas maletas puedo documentar?','My flight was delayed.|Mi vuelo se retrasó.','Where is gate twelve?|¿Dónde está la sala doce?','I missed my connection.|Perdí mi conexión.','I am here on vacation for two weeks.|Vengo de vacaciones por dos semanas.','I am staying at a hotel downtown.|Me voy a quedar en un hotel en el centro.','I have nothing to declare.|No tengo nada que declarar.','My suitcase did not arrive.|Mi maleta no llegó.','Could I have some water, please?|¿Me podría dar agua, por favor?','Is this seat taken?|¿Está ocupado este asiento?']},
{id:'restaurant',n:'Restaurante',en:'Restaurant',e:'🍽️',p:[
'A table for two, please.|Una mesa para dos, por favor.','Do you have a reservation?|¿Tiene reservación?','Can I see the menu?|¿Me deja ver el menú?','What do you recommend?|¿Qué me recomienda?','I would like the chicken, please.|Quisiera el pollo, por favor.','Could I get it without onions?|¿Me lo puede dar sin cebolla?','I am vegetarian.|Soy vegetariano.','This is not what I ordered.|Esto no es lo que pedí.','Could we have the check, please?|¿Nos trae la cuenta, por favor?','Can I pay by card?|¿Puedo pagar con tarjeta?','Is the tip included?|¿Está incluida la propina?','Everything was delicious.|Todo estuvo delicioso.']},
{id:'hotel',n:'Hotel',en:'Hotel',e:'🏨',p:[
'I have a reservation under the name Garcia.|Tengo una reservación a nombre de García.','What time is checkout?|¿A qué hora es la salida?','Is breakfast included?|¿Está incluido el desayuno?','What is the Wi-Fi password?|¿Cuál es la contraseña del wifi?','The air conditioning is not working.|El aire acondicionado no funciona.','Could I have an extra towel?|¿Me da una toalla extra?','Can you call a taxi for me?|¿Me puede pedir un taxi?','Can I leave my bags here?|¿Puedo dejar mis maletas aquí?','I would like to change rooms.|Me gustaría cambiar de cuarto.','Could I get a late checkout?|¿Puedo salir más tarde?']},
{id:'shopping',n:'De compras',en:'Shopping',e:'🛍️',p:[
'How much is this?|¿Cuánto cuesta esto?','Do you have this in a medium?|¿Lo tiene en mediana?','Can I try it on?|¿Me lo puedo probar?','Where are the fitting rooms?|¿Dónde están los probadores?','It is too tight.|Me queda muy apretado.','Do you have it in another color?|¿Lo tiene en otro color?','I am just looking, thanks.|Solo estoy viendo, gracias.','Is it on sale?|¿Está en oferta?','I would like to return this.|Quiero devolver esto.','Can I get a receipt?|¿Me da el ticket?']},
{id:'directions',n:'Pedir direcciones',en:'Asking for directions',e:'🗺️',p:[
'Excuse me, how do I get to the train station?|Disculpe, ¿cómo llego a la estación de tren?','Is it far from here?|¿Está lejos de aquí?','Go straight and turn left at the corner.|Siga derecho y dé vuelta a la izquierda en la esquina.','It is next to the bank.|Está al lado del banco.','It is about a ten minute walk.|Está como a diez minutos caminando.','Which bus goes downtown?|¿Qué camión va al centro?','Where can I buy a ticket?|¿Dónde compro un boleto?','I think I am lost.|Creo que estoy perdido.','Could you show me on the map?|¿Me lo puede enseñar en el mapa?']},
{id:'phone',n:'Por teléfono',en:'On the phone',e:'📞',p:[
'Hello, this is Carlos speaking.|Hola, habla Carlos.','Could I speak to Ms. Lopez, please?|¿Puedo hablar con la señora López?','She is not available right now.|No está disponible en este momento.','Can I leave a message?|¿Puedo dejar un mensaje?','Could you speak more slowly, please?|¿Podría hablar más despacio?','Sorry, the line is breaking up.|Perdón, se está cortando la llamada.','I will call you back later.|Te llamo más tarde.','What is the best number to reach you?|¿A qué número te localizo?']},
{id:'smalltalk',n:'Plática casual',en:'Small talk',e:'💬',p:[
'How is it going?|¿Cómo va todo?','What do you do for a living?|¿A qué te dedicas?','Where are you from originally?|¿De dónde eres originalmente?','How long have you lived here?|¿Cuánto tiempo llevas viviendo aquí?','What do you like to do on weekends?|¿Qué te gusta hacer los fines de semana?','Have you seen any good movies lately?|¿Has visto alguna buena película últimamente?','The weather is crazy today, right?|El clima está loco hoy, ¿verdad?','It was nice talking to you.|Me dio gusto platicar contigo.','Let\'s keep in touch.|Seguimos en contacto.','See you around!|¡Nos vemos!']},
{id:'work',n:'En el trabajo',en:'At work',e:'🏢',p:[
'Do you have a minute?|¿Tienes un minuto?','Let\'s schedule a meeting for Monday.|Agendemos una junta para el lunes.','I will send you the report by Friday.|Te mando el reporte a más tardar el viernes.','Could you give me a hand with this?|¿Me echas la mano con esto?','I am running a little late.|Voy un poco tarde.','Sorry, I did not catch that.|Perdón, no te entendí.','Let me double check and get back to you.|Déjame confirmar y te aviso.','That is a great idea.|Es una gran idea.','I agree with you.|Estoy de acuerdo contigo.','I see your point, but I think…|Entiendo tu punto, pero creo que…']},
{id:'opinions',n:'Dar tu opinión',en:'Giving opinions',e:'🗣️',p:[
'In my opinion, it is a good idea.|En mi opinión, es una buena idea.','I think that we should wait.|Creo que deberíamos esperar.','I totally agree.|Estoy totalmente de acuerdo.','I am not so sure about that.|No estoy tan seguro de eso.','I see what you mean, but…|Entiendo lo que dices, pero…','On the one hand… on the other hand…|Por un lado… por otro lado…','It depends on the situation.|Depende de la situación.','To be honest, I prefer the first option.|La verdad, prefiero la primera opción.']},
{id:'emergency',n:'Emergencias',en:'Emergencies',e:'🚨',p:[
'Help! Call an ambulance!|¡Ayuda! ¡Llamen una ambulancia!','Someone stole my wallet.|Alguien me robó la cartera.','I lost my passport.|Perdí mi pasaporte.','Where is the nearest police station?|¿Dónde está la estación de policía más cercana?','There has been an accident.|Hubo un accidente.','I need a doctor right now.|Necesito un doctor ahora mismo.','Please hurry!|¡Por favor, apúrense!','I need to contact my embassy.|Necesito contactar a mi embajada.']},
{id:'dating',n:'Amigos y citas',en:'Friends and dating',e:'💞',p:[
'Would you like to grab a coffee sometime?|¿Te gustaría ir por un café algún día?','Are you free this weekend?|¿Estás libre este fin de semana?','I had a great time tonight.|La pasé muy bien esta noche.','Can I have your number?|¿Me das tu número?','What kind of music are you into?|¿Qué música te gusta?','You look great today.|Te ves muy bien hoy.','Let me know when you get home.|Avísame cuando llegues a tu casa.','I miss you.|Te extraño.']},
{id:'bank',n:'Banco y dinero',en:'Bank and money',e:'🏦',p:[
'I would like to open an account.|Quisiera abrir una cuenta.','I need to withdraw some money.|Necesito retirar dinero.','The ATM kept my card.|El cajero se quedó con mi tarjeta.','What is the exchange rate today?|¿A cómo está el tipo de cambio hoy?','I want to transfer money to Mexico.|Quiero mandar dinero a México.','Is there a fee for this?|¿Esto tiene comisión?','I do not recognize this charge.|No reconozco este cargo.']},
];
window.SOUNDS=[
{id:'th',n:'TH (think, this)',e:'👅',tip:'Pon la punta de la lengua entre los dientes y sopla. Think no es "tink" ni "sink". En this y the la lengua va igual pero con vibración, como una "d" suave.',pairs:['think|sink|pensar|hundirse','thank|tank|agradecer|tanque','three|tree|tres|árbol','thin|tin|delgado|lata','bath|bat|baño|bate','mouth|mouse|boca|ratón','they|day|ellos|día','then|den|entonces|guarida']},
{id:'vb',n:'V y B',e:'🦷',tip:'En inglés la V se hace con los dientes de arriba tocando el labio de abajo, y suena. La B se hace juntando los dos labios. Very no suena igual que berry.',pairs:['very|berry|muy|baya','vote|boat|votar|barco','van|ban|camioneta|prohibir','vest|best|chaleco|el mejor','curve|curb|curva|banqueta','vet|bet|veterinario|apostar']},
{id:'ii',n:'I corta e I larga',e:'🐑',tip:'La i de ship es corta y relajada, casi entre "i" y "e". La ee de sheep es larga y con la boca estirada, como sonriendo. Cambiarlas cambia la palabra.',pairs:['ship|sheep|barco|oveja','live|leave|vivir|irse','sit|seat|sentarse|asiento','fill|feel|llenar|sentir','bit|beat|pedacito|golpear','hit|heat|pegar|calor','still|steal|todavía|robar','fit|feet|quedar bien|pies']},
{id:'ae',n:'A abierta (cat, hat)',e:'🐱',tip:'La a de cat se hace con la boca muy abierta y la lengua abajo, entre "a" y "e". No es igual a la o de hot ni a la u de cut.',pairs:['cat|cut|gato|cortar','hat|hot|sombrero|caliente','bag|bug|bolsa|bicho','cap|cup|gorra|taza','man|men|hombre|hombres','bad|bed|malo|cama','track|truck|pista|camión']},
{id:'h',n:'La H que sí suena',e:'💨',tip:'En inglés la H casi siempre suena, como una "j" muy suave: un poco de aire. Hat no es igual a at. Ojo: en hour y honest no suena.',pairs:['hat|at|sombrero|en','heat|eat|calor|comer','hear|ear|oír|oreja','hold|old|sostener|viejo','hair|air|cabello|aire','hill|ill|colina|enfermo']},
{id:'s',n:'S al inicio (Spain, school)',e:'🐍',tip:'No agregues una "e" antes de la S. Es Spain, no "Espain"; school, no "eschool". Empieza directo con el sonido de serpiente: sss-chool.',pairs:['school|eschool|escuela|(mal dicho)','Spain|Espain|España|(mal dicho)','star|estar|estrella|(mal dicho)','speak|espeak|hablar|(mal dicho)','student|estudent|estudiante|(mal dicho)'],speakOnly:true},
{id:'jy',n:'J, Y y CH',e:'🎵',tip:'La J de jet suena como "ch" con voz (dʒ). La Y de yet es como la "i" de "hielo". La CH de chair es como en español. Jello, yellow y chello suenan distinto.',pairs:['jet|yet|jet|todavía','jam|yam|mermelada|camote','joke|yolk|chiste|yema','cheap|jeep|barato|jeep','choke|joke|ahogarse|chiste','chain|Jane|cadena|Jane']},
{id:'sh',n:'SH y CH',e:'🤫',tip:'La SH es como pedir silencio: shhh, sin golpe. La CH tiene un golpecito al inicio: tch. Share no es igual a chair.',pairs:['share|chair|compartir|silla','ship|chip|barco|chip','sheep|cheap|oveja|barato','wash|watch|lavar|ver, reloj','shoes|choose|zapatos|elegir','cash|catch|efectivo|atrapar']},
{id:'ed',n:'Terminaciones -ED',e:'⏪',tip:'La -ed del pasado tiene 3 sonidos. Suena "t" después de p, k, f, s, sh, ch (walked = "wokt"). Suena "d" después de sonidos con voz (played = "pleid"). Solo suena "id" después de t o d (wanted, needed).',pairs:['walked|wanted|caminó|quiso','played|painted|jugó|pintó','stopped|started|paró|empezó','cleaned|needed|limpió|necesitó','laughed|landed|se rio|aterrizó','watched|waited|vio|esperó']},
{id:'final',n:'Consonantes al final',e:'🔚',tip:'En inglés se pronuncia la última letra. Si te comes la consonante final cambias la palabra: card no es car, and no es an.',pairs:['card|car|tarjeta|carro','bed|bet|cama|apostar','cold|coal|frío|carbón','mind|mine|mente|mío','send|sen|enviar|(mal dicho)','world|word|mundo|palabra']},
];
