// Diccionario visual de Fluent: vocabulario básico por temas, con dibujo, inglés y español.
// Formato de cada palabra: "dibujo|inglés|español". En Colores el dibujo es el color (#hex).
window.VOCAB=[
{id:'colors',n:'Colores',en:'Colors',e:'🎨',c:'#ff6b6b',w:[
'#e53935|red|rojo','#1e88e5|blue|azul','#43a047|green|verde','#fdd835|yellow|amarillo','#fb8c00|orange|naranja','#8e24aa|purple|morado','#ec407a|pink|rosa','#6d4c41|brown|café','#111111|black|negro','#ffffff|white|blanco','#9e9e9e|gray|gris','#80deea|light blue|azul claro','#1a237e|dark blue|azul marino','#c0ca33|lime green|verde limón','#d4af37|gold|dorado','#c0c0c0|silver|plateado','#40e0d0|turquoise|turquesa','#800020|burgundy|vino','#f5f5dc|beige|beige','#00897b|teal|verde azulado']},
{id:'pets',n:'Mascotas y granja',en:'Pets and farm animals',e:'🐶',c:'#ffb74d',w:[
'🐶|dog|perro','🐱|cat|gato','🐰|rabbit|conejo','🐹|hamster|hámster','🐟|fish|pez','🐦|bird|pájaro','🐢|turtle|tortuga','🐴|horse|caballo','🐮|cow|vaca','🐷|pig|cerdo, puerco','🐑|sheep|oveja','🐐|goat|cabra','🐔|chicken|gallina','🐓|rooster|gallo','🐤|chick|pollito','🦆|duck|pato','🦃|turkey|guajolote, pavo','🫏|donkey|burro','🐭|mouse|ratón','🐕|puppy|cachorro']},
{id:'wild',n:'Animales salvajes',en:'Wild animals',e:'🦁',c:'#f9a825',w:[
'🦁|lion|león','🐯|tiger|tigre','🐘|elephant|elefante','🦒|giraffe|jirafa','🦓|zebra|cebra','🐒|monkey|mono','🐻|bear|oso','🐼|panda|panda','🐺|wolf|lobo','🦊|fox|zorro','🦌|deer|venado','🐍|snake|serpiente, víbora','🐊|crocodile|cocodrilo','🦛|hippo|hipopótamo','🦏|rhino|rinoceronte','🐨|koala|koala','🦘|kangaroo|canguro','🦅|eagle|águila','🦉|owl|búho','🐿️|squirrel|ardilla']},
{id:'sea',n:'Mar e insectos',en:'Sea animals and bugs',e:'🐬',c:'#29b6f6',w:[
'🐬|dolphin|delfín','🐳|whale|ballena','🦈|shark|tiburón','🐙|octopus|pulpo','🦀|crab|cangrejo','🦐|shrimp|camarón','🐠|tropical fish|pez tropical','🦭|seal|foca','🐧|penguin|pingüino','🪼|jellyfish|medusa','🦋|butterfly|mariposa','🐝|bee|abeja','🐜|ant|hormiga','🕷️|spider|araña','🦟|mosquito|mosquito','🪰|fly|mosca','🐞|ladybug|catarina','🐌|snail|caracol','🪲|beetle|escarabajo','🦗|cricket|grillo']},
{id:'meals',n:'Comidas del día',en:'Meals',e:'🍽️',c:'#ef6c00',w:[
'🌅|breakfast|desayuno','☀️|lunch|almuerzo, comida','🌙|dinner|cena','🍪|snack|botana, refrigerio','🍰|dessert|postre','🥣|brunch|almuerzo tardío (brunch)','🍽️|meal|comida (cada comida del día)','😋|hungry|con hambre','🥤|thirsty|con sed','🤤|delicious|delicioso','🧑‍🍳|to cook|cocinar','🍴|to eat|comer','🥛|to drink|beber, tomar','🧾|the check|la cuenta','📋|menu|menú','🛒|groceries|el mandado','🥡|takeout|comida para llevar','🍳|homemade|hecho en casa','🔥|hot (spicy)|picante','🧊|cold|frío']},
{id:'food',n:'Comida',en:'Food',e:'🍔',c:'#f4511e',w:[
'🍞|bread|pan','🧀|cheese|queso','🥚|egg|huevo','🍚|rice|arroz','🫘|beans|frijoles','🌮|taco|taco','🌯|burrito|burrito','🍕|pizza|pizza','🍔|hamburger|hamburguesa','🌭|hot dog|hot dog, salchicha','🍟|french fries|papas fritas','🥗|salad|ensalada','🍲|soup|sopa','🍝|pasta|pasta','🥩|steak|bistec','🍗|chicken (food)|pollo','🐟|fish (food)|pescado','🥓|bacon|tocino','🥞|pancakes|hot cakes','🧈|butter|mantequilla','🍯|honey|miel','🧂|salt|sal','🌶️|chili pepper|chile','🍫|chocolate|chocolate','🍦|ice cream|helado','🍪|cookie|galleta','🎂|cake|pastel','🥜|peanuts|cacahuates','🍿|popcorn|palomitas','🥪|sandwich|sándwich, torta']},
{id:'fruits',n:'Frutas',en:'Fruits',e:'🍎',c:'#e53935',w:[
'🍎|apple|manzana','🍌|banana|plátano','🍊|orange (fruit)|naranja','🍋|lemon|limón amarillo','🍋‍🟩|lime|limón verde','🍇|grapes|uvas','🍓|strawberry|fresa','🍉|watermelon|sandía','🍈|melon|melón','🍍|pineapple|piña','🥭|mango|mango','🍑|peach|durazno','🍐|pear|pera','🍒|cherries|cerezas','🥥|coconut|coco','🥝|kiwi|kiwi','🫐|blueberries|moras azules','🥑|avocado|aguacate','🍅|tomato|jitomate','🍏|green apple|manzana verde']},
{id:'veg',n:'Verduras',en:'Vegetables',e:'🥕',c:'#7cb342',w:[
'🥕|carrot|zanahoria','🥔|potato|papa','🧅|onion|cebolla','🧄|garlic|ajo','🥬|lettuce|lechuga','🥦|broccoli|brócoli','🌽|corn|elote, maíz','🥒|cucumber|pepino','🫑|bell pepper|pimiento','🍆|eggplant|berenjena','🍄|mushroom|champiñón','🥗|spinach|espinaca','🫛|peas|chícharos','🎃|pumpkin|calabaza','🥬|cabbage|col','🫚|ginger|jengibre','🌿|cilantro|cilantro','🍠|sweet potato|camote','🧅|green onion|cebollín','🫒|olive|aceituna']},
{id:'drinks',n:'Bebidas',en:'Drinks',e:'🥤',c:'#8d6e63',w:[
'💧|water|agua','☕|coffee|café','🍵|tea|té','🥛|milk|leche','🧃|juice|jugo','🥤|soda|refresco','🍺|beer|cerveza','🍷|wine|vino','🧋|milkshake|malteada','🥥|coconut water|agua de coco','🍹|smoothie|licuado','🧊|ice|hielo','🫖|hot chocolate|chocolate caliente','🍶|lemonade|limonada','🥃|sparkling water|agua mineral','🫗|a glass of|un vaso de','☕|a cup of|una taza de','🍾|a bottle of|una botella de','🥫|a can of|una lata de','🥄|sugar|azúcar']},
{id:'kitchen',n:'Cocina y mesa',en:'Kitchen',e:'🍳',c:'#a1887f',w:[
'🍽️|plate|plato','🥣|bowl|tazón','☕|cup|taza','🥛|glass|vaso','🍴|fork|tenedor','🔪|knife|cuchillo','🥄|spoon|cuchara','🧻|napkin|servilleta','🍳|frying pan|sartén','🫕|pot|olla','🧊|refrigerator|refrigerador','🔥|stove|estufa','♨️|oven|horno','📦|microwave|microondas','🧽|sponge|esponja','🚰|sink|fregadero','🗑️|trash can|bote de basura','🧂|salt shaker|salero','🫖|kettle|tetera','🪑|table|mesa']},
{id:'numbers',n:'Números',en:'Numbers',e:'🔢',c:'#5c6bc0',w:[
'0️⃣|zero|cero','1️⃣|one|uno','2️⃣|two|dos','3️⃣|three|tres','4️⃣|four|cuatro','5️⃣|five|cinco','6️⃣|six|seis','7️⃣|seven|siete','8️⃣|eight|ocho','9️⃣|nine|nueve','🔟|ten|diez','1️⃣1️⃣|eleven|once','1️⃣2️⃣|twelve|doce','1️⃣5️⃣|fifteen|quince','2️⃣0️⃣|twenty|veinte','3️⃣0️⃣|thirty|treinta','5️⃣0️⃣|fifty|cincuenta','💯|one hundred|cien','🔢|one thousand|mil','🥇|first|primero','🥈|second|segundo','🥉|third|tercero']},
{id:'time',n:'Días, meses y estaciones',en:'Days, months and seasons',e:'📅',c:'#26a69a',w:[
'1️⃣|Monday|lunes','2️⃣|Tuesday|martes','3️⃣|Wednesday|miércoles','4️⃣|Thursday|jueves','5️⃣|Friday|viernes','6️⃣|Saturday|sábado','7️⃣|Sunday|domingo','❄️|January|enero','💘|February|febrero','🍀|March|marzo','🌧️|April|abril','🌷|May|mayo','☀️|June|junio','🎆|July|julio','🏖️|August|agosto','📚|September|septiembre','🎃|October|octubre','🦃|November|noviembre','🎄|December|diciembre','🌸|spring|primavera','🌞|summer|verano','🍂|fall|otoño','⛄|winter|invierno','📆|today|hoy','⏭️|tomorrow|mañana','⏮️|yesterday|ayer','🗓️|weekend|fin de semana']},
{id:'clock',n:'La hora',en:'Telling time',e:'⏰',c:'#00838f',w:[
'⏰|o\'clock|en punto','🕧|half past|y media','🕒|a quarter past|y cuarto','🕤|a quarter to|cuarto para','🌄|morning|mañana (parte del día)','🌞|noon|mediodía','🌇|afternoon|tarde','🌆|evening|noche (temprano)','🌃|night|noche','🕛|midnight|medianoche','⏱️|minute|minuto','⌛|hour|hora','⚡|second (time)|segundo','📅|day|día','🗓️|week|semana','📆|month|mes','🎉|year|año','⏩|early|temprano','⏪|late|tarde (con retraso)','🔁|always|siempre']},
{id:'weather',n:'Clima y naturaleza',en:'Weather and nature',e:'⛅',c:'#42a5f5',w:[
'☀️|sunny|soleado','☁️|cloudy|nublado','🌧️|rainy|lluvioso','⛈️|storm|tormenta','❄️|snow|nieve','🌬️|windy|con viento','🌫️|foggy|con neblina','🔥|hot|caliente, mucho calor','🥶|cold|frío','🌈|rainbow|arcoíris','⚡|lightning|relámpago','🌡️|temperature|temperatura','🌊|ocean|océano','🏖️|beach|playa','⛰️|mountain|montaña','🌋|volcano|volcán','🏞️|river|río','🌲|tree|árbol','🌸|flower|flor','🌙|moon|luna','⭐|star|estrella','☀️|sun|sol','🌍|earth|tierra','🏜️|desert|desierto','🌴|palm tree|palmera']},
{id:'body',n:'El cuerpo',en:'The body',e:'🧍',c:'#ec407a',w:[
'🗣️|head|cabeza','👁️|eye|ojo','👂|ear|oreja','👃|nose|nariz','👄|mouth|boca','🦷|tooth|diente','👅|tongue|lengua','💇|hair|cabello','😊|face|cara','🦵|leg|pierna','🦶|foot|pie','👣|feet|pies','💪|arm|brazo','✋|hand|mano','☝️|finger|dedo','🫀|heart|corazón','🧠|brain|cerebro','🦴|bone|hueso','🫁|lungs|pulmones','🤰|stomach|estómago','🦒|neck|cuello','🙆|shoulder|hombro','🦿|knee|rodilla','💅|nail|uña','🧔|beard|barba']},
{id:'health',n:'Salud',en:'Health',e:'🩺',c:'#ef5350',w:[
'🤒|sick|enfermo','🤕|headache|dolor de cabeza','🤧|cold (illness)|resfriado','🌡️|fever|fiebre','😷|cough|tos','🤢|stomachache|dolor de estómago','💊|pill|pastilla','💉|shot|inyección','🩹|band-aid|curita','🩺|doctor|doctor','👩‍⚕️|nurse|enfermera','🏥|hospital|hospital','🦷|dentist|dentista','🚑|ambulance|ambulancia','😴|tired|cansado','💪|healthy|sano','🧘|rest|descansar','🩸|blood|sangre','🤕|hurt|lastimado','💤|sleep|dormir']},
{id:'clothes',n:'Ropa',en:'Clothes',e:'👕',c:'#ab47bc',w:[
'👕|t-shirt|playera','👔|shirt|camisa','👖|pants|pantalón','👗|dress|vestido','🩳|shorts|shorts','👟|sneakers|tenis','👞|shoes|zapatos','👢|boots|botas','🧦|socks|calcetines','🧥|jacket|chamarra','🧣|scarf|bufanda','🧤|gloves|guantes','🧢|cap|gorra','👒|hat|sombrero','👓|glasses|lentes','🕶️|sunglasses|lentes de sol','👜|purse|bolsa','🎒|backpack|mochila','⌚|watch|reloj','💍|ring|anillo','🩲|underwear|ropa interior','👙|swimsuit|traje de baño','🥼|coat|abrigo','👘|skirt|falda','🩱|pajamas|pijama']},
{id:'house',n:'La casa',en:'The house',e:'🏠',c:'#8d6e63',w:[
'🏠|house|casa','🚪|door|puerta','🪟|window|ventana','🛋️|living room|sala','🛏️|bedroom|recámara','🛁|bathroom|baño','🍳|kitchen|cocina','🪜|stairs|escaleras','🏡|garden|jardín','🚗|garage|cochera','🛏️|bed|cama','🛋️|sofa|sillón','🪑|chair|silla','📺|TV|televisión','💡|lamp|lámpara','🪞|mirror|espejo','🚿|shower|regadera','🚽|toilet|excusado','🧺|laundry|ropa sucia','🔑|key|llave','🧹|broom|escoba','🖼️|picture|cuadro','⏰|alarm clock|despertador','🛁|towel|toalla','🧸|toy|juguete']},
{id:'family',n:'Familia y personas',en:'Family and people',e:'👨‍👩‍👧',c:'#ff7043',w:[
'👩|mother|mamá','👨|father|papá','👧|daughter|hija','👦|son|hijo','👭|sister|hermana','👬|brother|hermano','👵|grandmother|abuela','👴|grandfather|abuelo','👶|baby|bebé','🧒|child|niño','👩‍🦰|aunt|tía','🧔|uncle|tío','🧑‍🤝‍🧑|cousin|primo, prima','💑|wife|esposa','🤵|husband|esposo','👪|parents|padres','💞|girlfriend|novia','💙|boyfriend|novio','🤝|friend|amigo','🏘️|neighbor|vecino','👥|people|gente','🙋|man|hombre','🙋‍♀️|woman|mujer','👦|boy|niño','👧|girl|niña']},
{id:'jobs',n:'Profesiones',en:'Jobs',e:'👩‍🚀',c:'#5e35b1',w:[
'👨‍⚕️|doctor|médico','👩‍🏫|teacher|maestro','👮|police officer|policía','👨‍🚒|firefighter|bombero','👩‍🍳|cook|cocinero','🧑‍🌾|farmer|granjero','👷|construction worker|albañil','👨‍💻|programmer|programador','👩‍🔧|mechanic|mecánico','💇|hairdresser|estilista','👨‍✈️|pilot|piloto','🧑‍🚀|astronaut|astronauta','👩‍⚖️|lawyer|abogado','👨‍🎨|artist|artista','🎤|singer|cantante','👩‍💼|businesswoman|empresaria','🛒|cashier|cajero','🚕|driver|chofer','🍽️|waiter|mesero','🩺|nurse|enfermero','📸|photographer|fotógrafo','🔬|scientist|científico','🎬|actor|actor','⚽|athlete|atleta','✍️|writer|escritor']},
{id:'city',n:'Lugares',en:'Places',e:'🏙️',c:'#3949ab',w:[
'🏫|school|escuela','🏥|hospital|hospital','🏦|bank|banco','🏪|store|tienda','🛒|supermarket|supermercado','🍽️|restaurant|restaurante','☕|coffee shop|cafetería','🏨|hotel|hotel','✈️|airport|aeropuerto','🚉|train station|estación de tren','🏛️|museum|museo','📚|library|biblioteca','⛪|church|iglesia','🏞️|park|parque','🎬|movie theater|cine','💊|pharmacy|farmacia','🏋️|gym|gimnasio','🏟️|stadium|estadio','📮|post office|oficina de correos','⛽|gas station|gasolinera','🏢|office|oficina','🏬|mall|centro comercial','🛣️|street|calle','🌉|bridge|puente','🏖️|beach|playa']},
{id:'transport',n:'Transporte',en:'Transportation',e:'🚗',c:'#1e88e5',w:[
'🚗|car|carro','🚌|bus|camión, autobús','🚕|taxi|taxi','🚲|bicycle|bicicleta','🏍️|motorcycle|moto','🚆|train|tren','🚇|subway|metro','✈️|airplane|avión','🚢|ship|barco','⛵|boat|lancha, velero','🚁|helicopter|helicóptero','🚚|truck|camión de carga','🚑|ambulance|ambulancia','🚒|fire truck|camión de bomberos','🚓|police car|patrulla','🛴|scooter|scooter','🚶|on foot|a pie','🛑|stop|alto','🚦|traffic light|semáforo','🅿️|parking|estacionamiento','🎫|ticket|boleto','🧳|suitcase|maleta','🗺️|map|mapa','⛽|gas|gasolina']},
{id:'school',n:'Escuela y oficina',en:'School and office',e:'✏️',c:'#fbc02d',w:[
'✏️|pencil|lápiz','🖊️|pen|pluma','📓|notebook|cuaderno','📖|book|libro','📏|ruler|regla','✂️|scissors|tijeras','🖍️|crayon|crayón','🧮|calculator|calculadora','🎒|backpack|mochila','🧽|eraser|borrador','📎|paper clip|clip','📄|paper|papel','🖥️|computer|computadora','💻|laptop|laptop','🖨️|printer|impresora','📅|calendar|calendario','🗂️|folder|carpeta','📝|homework|tarea','📊|presentation|presentación','👩‍🎓|student|estudiante','🧑‍🏫|classroom|salón de clases','📋|test|examen','🔔|bell|campana','🗒️|desk|escritorio','🖌️|paint|pintura']},
{id:'sports',n:'Deportes y pasatiempos',en:'Sports and hobbies',e:'⚽',c:'#43a047',w:[
'⚽|soccer|futbol','🏀|basketball|basquetbol','⚾|baseball|beisbol','🏈|football|futbol americano','🎾|tennis|tenis','🏐|volleyball|voleibol','🏊|swimming|natación','🚴|cycling|ciclismo','🏃|running|correr','🥊|boxing|box','🏋️|weightlifting|pesas','🧘|yoga|yoga','⛳|golf|golf','🛹|skateboarding|patineta','🎮|video games|videojuegos','🎸|guitar|guitarra','🎹|piano|piano','🥁|drums|batería','🎨|painting|pintar','📷|photography|fotografía','💃|dancing|bailar','🎤|singing|cantar','📚|reading|leer','🧩|puzzle|rompecabezas','🎣|fishing|pescar']},
{id:'feelings',n:'Emociones',en:'Feelings',e:'😊',c:'#ffca28',w:[
'😊|happy|feliz','😢|sad|triste','😠|angry|enojado','😨|scared|asustado','😮|surprised|sorprendido','😴|sleepy|con sueño','😰|nervous|nervioso','😌|calm|tranquilo','🥱|bored|aburrido','🤩|excited|emocionado','😳|embarrassed|apenado','🤔|confused|confundido','😎|confident|seguro de sí mismo','🥰|in love|enamorado','😔|lonely|solo, solitario','😤|frustrated|frustrado','🙏|grateful|agradecido','😟|worried|preocupado','😁|proud|orgulloso','😇|relaxed|relajado']},
{id:'verbs',n:'Verbos básicos',en:'Basic verbs',e:'🏃',c:'#26c6da',w:[
'🍴|eat|comer','🥤|drink|beber','😴|sleep|dormir','🚶|walk|caminar','🏃|run|correr','🗣️|speak|hablar','👂|listen|escuchar','👀|see|ver','📖|read|leer','✍️|write|escribir','🎶|sing|cantar','💃|dance|bailar','🏊|swim|nadar','🍳|cook|cocinar','🧹|clean|limpiar','🛍️|buy|comprar','💼|work|trabajar','📚|study|estudiar','🎮|play|jugar','🛁|wash|lavar','🚗|drive|manejar','✈️|travel|viajar','🤝|help|ayudar','❤️|love|amar, encantar','🙌|open|abrir','🔒|close|cerrar','🎁|give|dar','🙋|ask|preguntar','💭|think|pensar','📞|call|llamar']},
{id:'adjectives',n:'Opuestos',en:'Opposites',e:'↔️',c:'#78909c',w:[
'🐘|big|grande','🐭|small|pequeño','🦒|tall|alto','🧸|short|bajo, corto','🚀|fast|rápido','🐢|slow|lento','🔥|hot|caliente','🧊|cold|frío','🆕|new|nuevo','🏚️|old|viejo','✨|clean|limpio','🗑️|dirty|sucio','😊|easy|fácil','🧗|hard|difícil','💰|expensive|caro','🏷️|cheap|barato','🌞|day|día','🌑|night|noche','⬆️|up|arriba','⬇️|down|abajo','👍|good|bueno','👎|bad|malo','💡|light|claro, ligero','🏋️|heavy|pesado','🧓|young|joven','🌕|full|lleno','🫙|empty|vacío']},
{id:'shapes',n:'Formas y posiciones',en:'Shapes and positions',e:'🔷',c:'#7e57c2',w:[
'⚪|circle|círculo','🟥|square|cuadrado','🔺|triangle|triángulo','▬|rectangle|rectángulo','⭐|star (shape)|estrella','❤️|heart (shape)|corazón','🔷|diamond|rombo','🥚|oval|óvalo','📦|in|dentro de','🔝|on|sobre, encima de','⬇️|under|debajo de','🔙|behind|detrás de','🔜|in front of|enfrente de','↔️|between|entre','👉|next to|al lado de','⬅️|left|izquierda','➡️|right|derecha','⬆️|straight ahead|derecho','📍|here|aquí','🗺️|there|allá']},
{id:'questions',n:'Preguntas y frases útiles',en:'Questions and useful phrases',e:'❓',c:'#e91e63',w:[
'❓|what|qué','👤|who|quién','📍|where|dónde','⏰|when|cuándo','🤔|why|por qué','🛠️|how|cómo','💲|how much|cuánto (cuesta)','🔢|how many|cuántos','👉|which|cuál','🙏|please|por favor','🙇|thank you|gracias','😊|you\'re welcome|de nada','😅|excuse me|disculpe','😔|I\'m sorry|lo siento','👋|hello|hola','👋|goodbye|adiós','👍|yes|sí','👎|no|no','🤷|I don\'t know|no sé','🐢|slowly, please|más despacio, por favor','🔁|can you repeat?|¿puede repetir?','🗣️|how do you say...?|¿cómo se dice...?','🆘|help!|¡ayuda!','🚻|where is the bathroom?|¿dónde está el baño?']},
{id:'tech',n:'Tecnología',en:'Technology',e:'📱',c:'#546e7a',w:[
'📱|cell phone|celular','💻|laptop|laptop','🖥️|computer|computadora','⌨️|keyboard|teclado','🖱️|mouse (computer)|ratón','🎧|headphones|audífonos','🔋|battery|batería','🔌|charger|cargador','📶|Wi-Fi|wifi','🔑|password|contraseña','📧|email|correo electrónico','💬|message|mensaje','📸|photo|foto','🎥|video|video','📲|app|aplicación','🌐|website|página web','🔍|search|buscar','⬇️|download|descargar','⬆️|upload|subir','🔗|link|enlace','📤|send|enviar','🔔|notification|notificación','🖨️|print|imprimir','☁️|the cloud|la nube']},
];
